# This contains params to be used by the stages to train or predict

prepare:
  split: 0.3
  seed: 2021

featurize:
  max_features: 2500
  n_grams: 3

train:
  seed: 7
  n_estimators: 100
  min_split: 16
