# This contains params to be used by the stages to train or predict

prepare:
  split: 0.20 
  seed: 7

featurize:
  max_features: 3000
  n_grams: 2

train:
  seed: 7
  n_estimators: 100
  min_split: 15