# It contains all the configs required in the project

artifacts:
  ARTIFACTS_DIR: artifacts
  PREPARED_DATA: prepared
  TRAIN_DATA: train.tsv
  TEST_DATA: test.tsv

source_data:
  data_dir: data
  data_file: data.xml

local_data_dirs:
  - path_to_local_data_1
  - path_to_local_data_2
